/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CRUD;

import controller.ShelvesJpaController;
import controller.UsersJpaController;
import controller.exceptions.NonexistentEntityException;
import entities.Shelves;
import entities.Users;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Juan
 */
public class CrudShelves extends javax.swing.JPanel {

    /**
     * Creates new form CrushShelv
     */
    public CrudShelves() {
        initComponents();
        loadTable();
        btnAdd.setEnabled(true);
        btnDelete.setEnabled(false);
        btnModify.setEnabled(false);
    }
    private void loadTable(){
        DefaultTableModel model= new DefaultTableModel();
        model.addColumn("id");
        model.addColumn("Name");
        model.addColumn("Categoriese");
        
        List<Shelves> listShelves = new ArrayList<Shelves>();
        ShelvesJpaController ujc =new ShelvesJpaController();
        listShelves = ujc.findShelvesEntities();
        System.out.println(listShelves);
        Object data[] =new Object[3];
        
        //Load objects to table.
        for (Shelves s:listShelves){
            
            data[0]=s.getId();
            data[1]=s.getName();
            data[2]=s.getCategories();
            model.addRow(data);
            
        }
        tblShelves.setModel(model);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLibrary = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnModify = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        lbIdBook = new javax.swing.JLabel();
        lblIdUsers = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        tblShelves = new javax.swing.JTable();
        txtCategorie = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();

        setLayout(null);

        lblLibrary.setText("Edit Shelves");
        add(lblLibrary);
        lblLibrary.setBounds(226, 6, 80, 16);

        btnAdd.setText("add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd);
        btnAdd.setBounds(530, 290, 50, 24);

        btnDelete.setText("delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete);
        btnDelete.setBounds(590, 290, 70, 24);

        btnExit.setText("exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        add(btnExit);
        btnExit.setBounds(750, 290, 60, 24);

        btnModify.setText("modify");
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });
        add(btnModify);
        btnModify.setBounds(670, 290, 70, 24);

        txtId.setEditable(false);
        add(txtId);
        txtId.setBounds(586, 56, 60, 24);

        lblId.setText("ID");
        add(lblId);
        lblId.setBounds(516, 56, 12, 16);

        lbIdBook.setText("Name");
        add(lbIdBook);
        lbIdBook.setBounds(516, 86, 60, 16);

        lblIdUsers.setText("Categories");
        add(lblIdUsers);
        lblIdUsers.setBounds(516, 116, 70, 16);

        tblShelves.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblShelves.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblShelves.setDoubleBuffered(true);
        tblShelves.setVerifyInputWhenFocusTarget(false);
        tblShelves.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblShelvesMouseClicked(evt);
            }
        });
        jScrollPane.setViewportView(tblShelves);

        add(jScrollPane);
        jScrollPane.setBounds(6, 36, 500, 307);
        add(txtCategorie);
        txtCategorie.setBounds(586, 116, 210, 24);
        add(txtName);
        txtName.setBounds(586, 86, 210, 24);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        Shelves shelve = new Shelves();
        
        //shelve.setId(Integer.parseInt(txtId.getText()));
        shelve.setName(txtName.getText());
        shelve.setCategories(txtCategorie.getText());
        
        ShelvesJpaController sjc = new ShelvesJpaController();
        sjc.create(shelve);
        loadTable();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        ShelvesJpaController sjc = new ShelvesJpaController();
        try {
            sjc.destroy(Integer.parseInt(txtId.getText()));
        } catch (NonexistentEntityException ex) {
            Logger.getLogger(CrudShelves.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtId.setText("");
        txtName.setText("");
        txtCategorie.setText("");
        loadTable();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        txtId.setText("");
        txtName.setText("");
        txtCategorie.setText("");
        btnAdd.setEnabled(true);
        btnDelete.setEnabled(false);
        btnModify.setEnabled(false);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
        Shelves shelve = new Shelves();
        
        shelve.setId(Integer.parseInt(txtId.getText()));
        shelve.setName(txtName.getText());
        shelve.setCategories(txtCategorie.getText());
        
        ShelvesJpaController sjc = new ShelvesJpaController();
        try {
            sjc.edit(shelve);
        } catch (Exception ex) {
            Logger.getLogger(CrudShelves.class.getName()).log(Level.SEVERE, null, ex);
        }
        loadTable();
    }//GEN-LAST:event_btnModifyActionPerformed

    private void tblShelvesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblShelvesMouseClicked
        txtId.setText(String.valueOf(tblShelves.getValueAt(tblShelves.getSelectedRow(),0)));
        txtName.setText(String.valueOf(tblShelves.getValueAt(tblShelves.getSelectedRow(),1)));
        txtCategorie.setText(String.valueOf(tblShelves.getValueAt(tblShelves.getSelectedRow(),2)));
        btnAdd.setEnabled(false);
        btnDelete.setEnabled(true);
        btnModify.setEnabled(true);
        btnExit.setEnabled(true);
    }//GEN-LAST:event_tblShelvesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnModify;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel lbIdBook;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblIdUsers;
    private javax.swing.JLabel lblLibrary;
    private javax.swing.JTable tblShelves;
    private javax.swing.JTextField txtCategorie;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
