/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CRUD;

/**
 *
 * @author Ricardo
 */
public class CrudUsers extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public CrudUsers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLibrary = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnModify = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        lbIdBook = new javax.swing.JLabel();
        lblIdUsers = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        tblBorrowed = new javax.swing.JTable();
        ReturnedTrue = new javax.swing.JRadioButton();
        ReturnedFalse = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();

        setLayout(null);

        lblLibrary.setText("Edit Users");
        add(lblLibrary);
        lblLibrary.setBounds(226, 6, 80, 16);

        btnAdd.setText("add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd);
        btnAdd.setBounds(530, 290, 50, 24);

        btnDelete.setText("delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete);
        btnDelete.setBounds(590, 290, 70, 24);

        btnExit.setText("exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        add(btnExit);
        btnExit.setBounds(750, 290, 60, 24);

        btnModify.setText("modify");
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });
        add(btnModify);
        btnModify.setBounds(670, 290, 70, 24);

        txtId.setEditable(false);
        add(txtId);
        txtId.setBounds(586, 56, 60, 24);

        lblId.setText("ID");
        add(lblId);
        lblId.setBounds(516, 56, 12, 16);

        lbIdBook.setText("firstName");
        add(lbIdBook);
        lbIdBook.setBounds(516, 86, 60, 16);

        lblIdUsers.setText("LastName");
        add(lblIdUsers);
        lblIdUsers.setBounds(516, 116, 60, 16);

        lblDate.setText("Password");
        add(lblDate);
        lblDate.setBounds(516, 146, 70, 16);

        tblBorrowed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblBorrowed.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblBorrowed.setDoubleBuffered(true);
        tblBorrowed.setVerifyInputWhenFocusTarget(false);
        tblBorrowed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBorrowedMouseClicked(evt);
            }
        });
        jScrollPane.setViewportView(tblBorrowed);

        add(jScrollPane);
        jScrollPane.setBounds(6, 36, 500, 307);

        ReturnedTrue.setText("Admin");
        ReturnedTrue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnedTrueActionPerformed(evt);
            }
        });
        add(ReturnedTrue);
        ReturnedTrue.setBounds(600, 220, 90, 28);

        ReturnedFalse.setSelected(true);
        ReturnedFalse.setText("Not Admin");
        add(ReturnedFalse);
        ReturnedFalse.setBounds(600, 250, 110, 28);

        jLabel1.setText("Returned");
        add(jLabel1);
        jLabel1.setBounds(520, 230, 70, 16);
        add(jTextField1);
        jTextField1.setBounds(586, 116, 210, 24);
        add(jTextField2);
        jTextField2.setBounds(586, 86, 210, 24);
        add(jTextField3);
        jTextField3.setBounds(586, 146, 210, 24);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        //        //Borrowed borrowed  = new Borrowed();
        //        Borrowed borrowed = new Borrowed();
        //        //borrowed.setId(Integer.parseInt(txtIdBooks.getText()));
        //        borrowed.setIdBooks((Books)cbIDBooks.getSelectedItem());
        //        borrowed.setIdUsers((CrudUsers) cbIDUsers.getSelectedItem());
        //        borrowed.setDate(dChoserDate.getDate());
        //        borrowed.setDueDate(dChoserDueDate.getDate());
        //        borrowed.setReturned(ReturnedTrue.isSelected());
        //        BorrowedJpaController bjc = new BorrowedJpaController();
        //        bjc.create(borrowed);
        //        loadTable();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        //        BorrowedJpaController bjc = new BorrowedJpaController();
        //        try {
            //            bjc.destroy(Integer.parseInt(txtId.getText()));
            //        } catch (NonexistentEntityException ex) {
            //            Logger.getLogger(WindowBorrowed.class.getName()).log(Level.SEVERE, null, ex);
            //        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        //        btnAdd.setEnabled(true);
        //        btnDelete.setEnabled(false);
        //        btnModify.setEnabled(false);
        //        //dChoserDueDate.cleanup();
        //        //btnExit.setEnabled(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
        //        Borrowed borrowed = new Borrowed();
        //        borrowed.setId(Integer.parseInt(txtId.getText()));
        //        borrowed.setIdBooks((Books)cbIDBooks.getSelectedItem());
        //        borrowed.setIdUsers((CrudUsers) cbIDUsers.getSelectedItem());
        //        borrowed.setDate(dChoserDate.getDate());
        //        borrowed.setDueDate(dChoserDueDate.getDate());
        //        borrowed.setReturned(ReturnedTrue.isSelected());
        //        BorrowedJpaController bjc = new BorrowedJpaController();
        //
        //        try {
            //            bjc.edit(borrowed);
            //        } catch (Exception ex) {
            //            Logger.getLogger(WindowBorrowed.class.getName()).log(Level.SEVERE, null, ex);
            //        }
        //        loadTable();
    }//GEN-LAST:event_btnModifyActionPerformed

    private void tblBorrowedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBorrowedMouseClicked
        //        System.out.println(tblBorrowed.getValueAt(0, 1).getClass());
        //        UsersJpaController ujc= new UsersJpaController();
        //        CrudUsers u= (CrudUsers) tblBorrowed.getValueAt(0, 1);
        //        txtId.setText(String.valueOf(tblBorrowed.getValueAt(tblBorrowed.getSelectedRow(),0)));
        //        cbIDUsers.getModel().setSelectedItem(tblBorrowed.getValueAt(tblBorrowed.getSelectedRow(),1));
        //        cbIDBooks.getModel().setSelectedItem(tblBorrowed.getValueAt(tblBorrowed.getSelectedRow(),2));
        //
        //        try {
            //            dChoserDate.setDate(new SimpleDateFormat("dd/MM/yyyy").parse(String.valueOf(tblBorrowed.getValueAt(tblBorrowed.getSelectedRow(),3))));
            //            dChoserDueDate.setDate(new SimpleDateFormat("dd/MM/yyyy").parse(String.valueOf(tblBorrowed.getValueAt(tblBorrowed.getSelectedRow(),4))));
            //
            //        } catch (ParseException ex) {
            //            Logger.getLogger(WindowBorrowed.class.getName()).log(Level.SEVERE, null, ex);
            //        }
        //        btnAdd.setEnabled(false);
        //        btnDelete.setEnabled(true);
        //        btnModify.setEnabled(true);
        //        btnExit.setEnabled(true);
    }//GEN-LAST:event_tblBorrowedMouseClicked

    private void ReturnedTrueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnedTrueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReturnedTrueActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ReturnedFalse;
    private javax.swing.JRadioButton ReturnedTrue;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnModify;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lbIdBook;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblIdUsers;
    private javax.swing.JLabel lblLibrary;
    private javax.swing.JTable tblBorrowed;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
