/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CRUD;

import controller.BooksJpaController;
import controller.BorrowedJpaController;
import controller.UsersJpaController;
import entities.Books;
import entities.Borrowed;
import entities.Users;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Juan
 */
public class CrudUsers extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public CrudUsers() {
        initComponents();
        loadTable();
        btnAdd.setEnabled(true);
        btnDelete.setEnabled(false);
        btnModify.setEnabled(false);
    }
    private void loadTable(){
        DefaultTableModel model= new DefaultTableModel();
        model.addColumn("id");
        model.addColumn("firstName");
        model.addColumn("lastName");
        model.addColumn("Password");
        model.addColumn("Admin");
        List<Users> listUsers = new ArrayList<Users>();
        UsersJpaController ujc =new UsersJpaController();
        listUsers = ujc.findUsersEntities();
        System.out.println(listUsers);
        Object data[] =new Object[5];
        
        //Load objects to table.
        for (Users u:listUsers){
            
            data[0]=u.getId();
            data[1]=u.getFistName();
            data[2]=u.getLastName();
            data[3]=u.getPassword();
            data[4]=u.getUserType();
            model.addRow(data);
        }
        tblUsers.setModel(model);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLibrary = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnModify = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        lbIdBook = new javax.swing.JLabel();
        lblIdUsers = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        ReturnedTrue = new javax.swing.JRadioButton();
        ReturnedFalse = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();

        setLayout(null);

        lblLibrary.setText("Edit Users");
        add(lblLibrary);
        lblLibrary.setBounds(226, 6, 80, 16);

        btnAdd.setText("add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd);
        btnAdd.setBounds(530, 290, 50, 24);

        btnDelete.setText("delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete);
        btnDelete.setBounds(590, 290, 70, 24);

        btnExit.setText("exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        add(btnExit);
        btnExit.setBounds(750, 290, 60, 24);

        btnModify.setText("modify");
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });
        add(btnModify);
        btnModify.setBounds(670, 290, 70, 24);
        add(txtId);
        txtId.setBounds(586, 56, 60, 24);

        lblId.setText("ID");
        add(lblId);
        lblId.setBounds(516, 56, 12, 16);

        lbIdBook.setText("first Name");
        add(lbIdBook);
        lbIdBook.setBounds(516, 86, 60, 16);

        lblIdUsers.setText("Last Name");
        add(lblIdUsers);
        lblIdUsers.setBounds(516, 116, 70, 16);

        lblDate.setText("Password");
        add(lblDate);
        lblDate.setBounds(516, 146, 70, 16);

        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblUsers.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblUsers.setDoubleBuffered(true);
        tblUsers.setVerifyInputWhenFocusTarget(false);
        tblUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsersMouseClicked(evt);
            }
        });
        jScrollPane.setViewportView(tblUsers);

        add(jScrollPane);
        jScrollPane.setBounds(6, 36, 500, 307);

        ReturnedTrue.setText("True");
        ReturnedTrue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnedTrueActionPerformed(evt);
            }
        });
        add(ReturnedTrue);
        ReturnedTrue.setBounds(600, 220, 90, 28);

        ReturnedFalse.setSelected(true);
        ReturnedFalse.setText("False");
        ReturnedFalse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnedFalseActionPerformed(evt);
            }
        });
        add(ReturnedFalse);
        ReturnedFalse.setBounds(600, 250, 110, 28);

        jLabel1.setText("Admin");
        add(jLabel1);
        jLabel1.setBounds(520, 230, 70, 16);
        add(txtLastName);
        txtLastName.setBounds(586, 116, 210, 24);
        add(txtFirstName);
        txtFirstName.setBounds(586, 86, 210, 24);
        add(txtPassword);
        txtPassword.setBounds(586, 146, 210, 24);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        Users user = new Users();
        
        user.setId(Integer.parseInt(txtId.getText()));
        user.setFistName(txtFirstName.getText());
        user.setLastName(txtLastName.getText());
        user.setPassword(txtPassword.getText());
        user.setUserType(ReturnedTrue.isSelected());
        
        UsersJpaController ujc = new UsersJpaController();
        try {
            ujc.create(user);
        } catch (Exception ex) {
            Logger.getLogger(CrudUsers.class.getName()).log(Level.SEVERE, null, ex);
        }
        loadTable();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        UsersJpaController ujc = new UsersJpaController();
        try {
            ujc.destroy(Integer.parseInt(txtId.getText()));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,"This user has data in another table or has already been deleted" );
            //Logger.getLogger(CrudUsers.class.getName()).log(Level.FINEST, null, ex);
        }
        loadTable(); 
        txtFirstName.setText("");
        txtId.setText("");
        txtLastName.setText("");
        txtPassword.setText("");
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        txtFirstName.setText("");
        txtId.setText("");
        txtLastName.setText("");
        txtPassword.setText("");
        ReturnedFalse.setSelected(true);
        btnAdd.setEnabled(true);
        btnDelete.setEnabled(false);
        btnModify.setEnabled(false);
        
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
        Users user = new Users();
        
        user.setId(Integer.parseInt(txtId.getText()));
        user.setFistName(txtFirstName.getText());
        user.setLastName(txtLastName.getText());
        user.setPassword(txtPassword.getText());
        user.setUserType(ReturnedTrue.isSelected());
        //user.setBorrowedCollection();
        
        UsersJpaController ujc = new UsersJpaController();
        try {
            ujc.edit(user);
        } catch (Exception ex) {
            Logger.getLogger(CrudUsers.class.getName()).log(Level.SEVERE, null, ex);
        }
        loadTable();
    }//GEN-LAST:event_btnModifyActionPerformed

    private void tblUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsersMouseClicked
        txtId.setText(String.valueOf(tblUsers.getValueAt(tblUsers.getSelectedRow(),0)));
        txtFirstName.setText(String.valueOf(tblUsers.getValueAt(tblUsers.getSelectedRow(),1)));
        txtLastName.setText(String.valueOf(tblUsers.getValueAt(tblUsers.getSelectedRow(),2)));
        txtPassword.setText(String.valueOf(tblUsers.getValueAt(tblUsers.getSelectedRow(),3)));
        ReturnedTrue.setSelected(Boolean.parseBoolean(String.valueOf(tblUsers.getValueAt(tblUsers.getSelectedRow(),4))));
        ReturnedFalse.setSelected(!Boolean.parseBoolean(String.valueOf(tblUsers.getValueAt(tblUsers.getSelectedRow(),4))));
        btnAdd.setEnabled(false);
        btnDelete.setEnabled(true);
        btnModify.setEnabled(true);
        btnExit.setEnabled(true);
    }//GEN-LAST:event_tblUsersMouseClicked

    private void ReturnedTrueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnedTrueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReturnedTrueActionPerformed

    private void ReturnedFalseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnedFalseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReturnedFalseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ReturnedFalse;
    private javax.swing.JRadioButton ReturnedTrue;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnModify;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel lbIdBook;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblIdUsers;
    private javax.swing.JLabel lblLibrary;
    private javax.swing.JTable tblUsers;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPassword;
    // End of variables declaration//GEN-END:variables
}
