/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CRUD;

/**
 *
 * @author Ricardo
 */
public class CrudBooks extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public CrudBooks() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        booksPane = new javax.swing.JPanel();
        lblLibrary = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnModify = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        txtTitle = new javax.swing.JTextField();
        txtEditorial = new javax.swing.JTextField();
        txtAuthor = new javax.swing.JTextField();
        txtExistences = new javax.swing.JTextField();
        txtShelve = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblEditorial = new javax.swing.JLabel();
        lblAuthor = new javax.swing.JLabel();
        lblExistences = new javax.swing.JLabel();
        lblShelve = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        tblBooks = new javax.swing.JTable();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();

        setLayout(null);

        booksPane.setMinimumSize(new java.awt.Dimension(440, 840));
        booksPane.setLayout(null);

        lblLibrary.setText("Library");
        booksPane.add(lblLibrary);
        lblLibrary.setBounds(226, 6, 37, 16);

        btnAdd.setText("add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        booksPane.add(btnAdd);
        btnAdd.setBounds(516, 256, 50, 24);

        btnDelete.setText("delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        booksPane.add(btnDelete);
        btnDelete.setBounds(576, 256, 70, 24);

        btnExit.setText("exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        booksPane.add(btnExit);
        btnExit.setBounds(736, 256, 60, 24);

        btnModify.setText("modify");
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });
        booksPane.add(btnModify);
        btnModify.setBounds(656, 256, 70, 24);

        txtId.setFocusable(false);
        booksPane.add(txtId);
        txtId.setBounds(586, 56, 60, 24);
        booksPane.add(txtTitle);
        txtTitle.setBounds(586, 86, 220, 24);
        booksPane.add(txtEditorial);
        txtEditorial.setBounds(586, 116, 220, 24);
        booksPane.add(txtAuthor);
        txtAuthor.setBounds(586, 146, 220, 24);
        booksPane.add(txtExistences);
        txtExistences.setBounds(586, 176, 220, 24);
        booksPane.add(txtShelve);
        txtShelve.setBounds(586, 206, 220, 24);

        lblId.setText("ID");
        booksPane.add(lblId);
        lblId.setBounds(516, 56, 12, 16);

        lblTitle.setText("Title");
        booksPane.add(lblTitle);
        lblTitle.setBounds(516, 86, 23, 16);

        lblEditorial.setText("Editorial");
        booksPane.add(lblEditorial);
        lblEditorial.setBounds(516, 116, 45, 16);

        lblAuthor.setText("Author");
        booksPane.add(lblAuthor);
        lblAuthor.setBounds(516, 146, 35, 16);

        lblExistences.setText("Existences");
        booksPane.add(lblExistences);
        lblExistences.setBounds(516, 176, 60, 16);

        lblShelve.setText("Shelve");
        booksPane.add(lblShelve);
        lblShelve.setBounds(516, 206, 37, 16);

        tblBooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblBooks.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblBooks.setDoubleBuffered(true);
        tblBooks.getTableHeader().setResizingAllowed(false);
        tblBooks.getTableHeader().setReorderingAllowed(false);
        tblBooks.setVerifyInputWhenFocusTarget(false);
        tblBooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBooksMouseClicked(evt);
            }
        });
        jScrollPane.setViewportView(tblBooks);

        booksPane.add(jScrollPane);
        jScrollPane.setBounds(6, 36, 500, 307);

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jFormattedTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField1ActionPerformed(evt);
            }
        });
        booksPane.add(jFormattedTextField1);
        jFormattedTextField1.setBounds(580, 360, 210, 30);

        add(booksPane);
        booksPane.setBounds(0, 0, 838, 474);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        //        Books books = new Books();
        //        books.setAuthor(txtAuthor.getText());
        //        books.setEditorial(txtEditorial.getText());
        //        books.setExistences(Integer.parseInt(txtExistences.getText()));
        //        //books.setId(WIDTH);
        //        books.setShelve(txtShelve.getText());
        //        books.setTitle(txtTitle.getText());
        //        BooksJpaController bjc =new BooksJpaController();
        //        bjc.create(books);
        //        loadTable();
        //        /*Book book = new Book(Integer.parseInt(txtId.getText()), txtTitle.getText(),
            //            txtEditorial.getText(), txtAuthor.getText(),
            //            Integer.parseInt(txtExistences.getText()), txtShelve.getText());
        //
        //        //System.out.print(book.toString());
        //        if(book.add()){
            //            JOptionPane.showMessageDialog(null,"Succesfully added");
            //        }
        //        else{
            //            JOptionPane.showMessageDialog(null,"Problem");
            //        }*/
        //
        //txtAuthor.getText();        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        //        try {
            //            Books books = new Books();
            //            BooksJpaController bjc =new BooksJpaController();
            //            System.out.println("entero = "+Integer.parseInt(txtId.getText()));
            //            bjc.destroy(Integer.parseInt(txtId.getText()));
            //            loadTable();
            //
            //            // TODO add your handling code here:
            //        } catch (NonexistentEntityException ex) {
            //            Logger.getLogger(Visual.class.getName()).log(Level.SEVERE, null, ex);
            //        } catch (IllegalOrphanException ex) {
            //            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
            //        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        //        btnAdd.setEnabled(true);
        //        btnDelete.setEnabled(false);
        //        btnModify.setEnabled(false);
        //        btnExit.setEnabled(false);
        //        txtId.setText("");
        //        txtTitle.setText("");
        //        txtEditorial.setText("");
        //        txtAuthor.setText("");
        //        txtExistences.setText("");
        //        txtShelve.setText("");
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
        //
        //        //cambiar despues
        //        int id= Integer.parseInt(txtId.getText());
        //        Books books = new Books();
        //        books.setId(id);
        //        books.setAuthor(txtAuthor.getText());
        //        books.setEditorial(txtEditorial.getText());
        //        books.setExistences(Integer.parseInt(txtExistences.getText()));
        //        //books.setId(WIDTH);
        //        books.setShelve(txtShelve.getText());
        //        books.setTitle(txtTitle.getText());
        //        BooksJpaController bjc =new BooksJpaController();
        //        try {
            //            bjc.edit(books);
            //        } catch (Exception ex) {
            //            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
            //        }
        //        loadTable();
        //
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModifyActionPerformed

    private void tblBooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBooksMouseClicked

        txtId.setText(String.valueOf(tblBooks.getValueAt(tblBooks.getSelectedRow(), 0)));
        txtTitle.setText(String.valueOf(tblBooks.getValueAt(tblBooks.getSelectedRow(), 1)));
        txtEditorial.setText(String.valueOf(tblBooks.getValueAt(tblBooks.getSelectedRow(), 2)));
        txtAuthor.setText(String.valueOf(tblBooks.getValueAt(tblBooks.getSelectedRow(), 3)));
        txtExistences.setText(String.valueOf(tblBooks.getValueAt(tblBooks.getSelectedRow(), 4)));
        txtShelve.setText(String.valueOf(tblBooks.getValueAt(tblBooks.getSelectedRow(), 5)));

        btnAdd.setEnabled(false);
        btnDelete.setEnabled(true);
        btnModify.setEnabled(true);
        btnExit.setEnabled(true);
    }//GEN-LAST:event_tblBooksMouseClicked

    private void jFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel booksPane;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnModify;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel lblAuthor;
    private javax.swing.JLabel lblEditorial;
    private javax.swing.JLabel lblExistences;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblLibrary;
    private javax.swing.JLabel lblShelve;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblBooks;
    private javax.swing.JTextField txtAuthor;
    private javax.swing.JTextField txtEditorial;
    private javax.swing.JTextField txtExistences;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtShelve;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables
}
