/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CRUD;

import controller.BooksJpaController;
import controller.BorrowedJpaController;
import controller.UsersJpaController;
import controller.exceptions.IllegalOrphanException;
import controller.exceptions.NonexistentEntityException;
import entities.Books;
import entities.Borrowed;
import entities.Users;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ricardo
 */
public class WindowBorrowed extends javax.swing.JPanel {

    /**
     * Creates new form panelPrueba
     */
    public WindowBorrowed() {
        initComponents();
        loadTable();
        btnAdd.setEnabled(true);
        btnDelete.setEnabled(false);
        btnModify.setEnabled(false);
        
    }
    private void loadTable(){
        DefaultTableModel model= new DefaultTableModel();
        model.addColumn("id");
        model.addColumn("IdUsers");
        model.addColumn("IdBooks");
        model.addColumn("Date");
        model.addColumn("DueDate");
        model.addColumn("getReturned");
        List<Borrowed> listBorrowed = new ArrayList<Borrowed>();
        BorrowedJpaController bjc =new BorrowedJpaController();
        listBorrowed = bjc.findBorrowedEntities();

        Object data[] =new Object[6];
        
        //Load objects to table.
        for (Borrowed b:listBorrowed){
            DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            data[0]=b.getId();
            data[1]=b.getIdUsers();
            data[2]=b.getIdBooks();
            data[3]=dateFormat.format(b.getDate());
            data[4]=dateFormat.format(b.getDueDate());
            data[5]=b.getReturned();
            model.addRow(data);
        }
        //load comboBox users
        for (Users u:(new UsersJpaController()).findUsersEntities()){
            cbIDUsers.addItem(u);
        }
        //load Combobox Books
        for (Books b:(new BooksJpaController()).findBooksEntities()){
            cbIDBooks.addItem(b);
        }
        tblBorrowed.setModel(model);
        
        
        
    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupReturned = new javax.swing.ButtonGroup();
        lblLibrary = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnModify = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        lbIdBook = new javax.swing.JLabel();
        lblIdUsers = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblDueDate = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        tblBorrowed = new javax.swing.JTable();
        dChoserDate = new com.toedter.calendar.JDateChooser();
        ReturnedTrue = new javax.swing.JRadioButton();
        ReturnedFalse = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        cbIDUsers = new javax.swing.JComboBox<>();
        cbIDBooks = new javax.swing.JComboBox<>();
        dChoserDueDate = new com.toedter.calendar.JDateChooser();

        setLayout(null);

        lblLibrary.setText("Edit Borrowed");
        add(lblLibrary);
        lblLibrary.setBounds(226, 6, 80, 16);

        btnAdd.setText("add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd);
        btnAdd.setBounds(530, 290, 50, 24);

        btnDelete.setText("delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete);
        btnDelete.setBounds(590, 290, 70, 24);

        btnExit.setText("exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        add(btnExit);
        btnExit.setBounds(750, 290, 60, 24);

        btnModify.setText("modify");
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });
        add(btnModify);
        btnModify.setBounds(670, 290, 70, 24);

        txtId.setEditable(false);
        add(txtId);
        txtId.setBounds(586, 56, 60, 24);

        lblId.setText("ID");
        add(lblId);
        lblId.setBounds(516, 56, 12, 16);

        lbIdBook.setText("ID Book");
        add(lbIdBook);
        lbIdBook.setBounds(516, 86, 60, 16);

        lblIdUsers.setText("ID Users");
        add(lblIdUsers);
        lblIdUsers.setBounds(516, 116, 60, 16);

        lblDate.setText("Date");
        add(lblDate);
        lblDate.setBounds(516, 146, 50, 16);

        lblDueDate.setText("Due Date");
        add(lblDueDate);
        lblDueDate.setBounds(516, 176, 60, 16);

        tblBorrowed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblBorrowed.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblBorrowed.setDoubleBuffered(true);
        tblBorrowed.setVerifyInputWhenFocusTarget(false);
        tblBorrowed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBorrowedMouseClicked(evt);
            }
        });
        jScrollPane.setViewportView(tblBorrowed);

        add(jScrollPane);
        jScrollPane.setBounds(6, 36, 500, 307);

        dChoserDate.setDateFormatString("dd/MM/yyyy");
        add(dChoserDate);
        dChoserDate.setBounds(586, 146, 210, 24);

        btnGroupReturned.add(ReturnedTrue);
        ReturnedTrue.setText("yes");
        ReturnedTrue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnedTrueActionPerformed(evt);
            }
        });
        add(ReturnedTrue);
        ReturnedTrue.setBounds(600, 220, 51, 28);

        btnGroupReturned.add(ReturnedFalse);
        ReturnedFalse.setSelected(true);
        ReturnedFalse.setText("no");
        add(ReturnedFalse);
        ReturnedFalse.setBounds(600, 250, 46, 28);

        jLabel1.setText("Returned");
        add(jLabel1);
        jLabel1.setBounds(520, 230, 70, 16);

        cbIDUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbIDUsersActionPerformed(evt);
            }
        });
        add(cbIDUsers);
        cbIDUsers.setBounds(586, 116, 210, 26);

        cbIDBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbIDBooksActionPerformed(evt);
            }
        });
        add(cbIDBooks);
        cbIDBooks.setBounds(586, 86, 210, 26);

        dChoserDueDate.setDateFormatString("dd/MM/yyyy");
        add(dChoserDueDate);
        dChoserDueDate.setBounds(586, 176, 210, 24);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        //Borrowed borrowed  = new Borrowed();
        Borrowed borrowed = new Borrowed();
        //borrowed.setId(Integer.parseInt(txtIdBooks.getText()));
        borrowed.setIdBooks((Books)cbIDBooks.getSelectedItem());
        borrowed.setIdUsers((Users) cbIDUsers.getSelectedItem());
        borrowed.setDate(dChoserDate.getDate());
        borrowed.setDueDate(dChoserDueDate.getDate());
        borrowed.setReturned(ReturnedTrue.isSelected());
        BorrowedJpaController bjc = new BorrowedJpaController();
        bjc.create(borrowed);
        loadTable();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        BorrowedJpaController bjc = new BorrowedJpaController();
        try {
            bjc.destroy(Integer.parseInt(txtId.getText()));
        } catch (NonexistentEntityException ex) {
            Logger.getLogger(WindowBorrowed.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        btnAdd.setEnabled(true);
        btnDelete.setEnabled(false);
        btnModify.setEnabled(false);
        //dChoserDueDate.cleanup();
        //btnExit.setEnabled(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    private void tblBorrowedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBorrowedMouseClicked
        System.out.println(tblBorrowed.getValueAt(0, 1).getClass());
        UsersJpaController ujc= new UsersJpaController();
        Users u= (Users) tblBorrowed.getValueAt(0, 1);
        txtId.setText(String.valueOf(tblBorrowed.getValueAt(tblBorrowed.getSelectedRow(),0)));
        cbIDUsers.getModel().setSelectedItem(tblBorrowed.getValueAt(tblBorrowed.getSelectedRow(),1));
        cbIDBooks.getModel().setSelectedItem(tblBorrowed.getValueAt(tblBorrowed.getSelectedRow(),2));
        
        try {
            dChoserDate.setDate(new SimpleDateFormat("dd/MM/yyyy").parse(String.valueOf(tblBorrowed.getValueAt(tblBorrowed.getSelectedRow(),3))));
            dChoserDueDate.setDate(new SimpleDateFormat("dd/MM/yyyy").parse(String.valueOf(tblBorrowed.getValueAt(tblBorrowed.getSelectedRow(),4))));
            
        } catch (ParseException ex) {
            Logger.getLogger(WindowBorrowed.class.getName()).log(Level.SEVERE, null, ex);
        }
        btnAdd.setEnabled(false);
        btnDelete.setEnabled(true);
        btnModify.setEnabled(true);
        btnExit.setEnabled(true);
        
    }//GEN-LAST:event_tblBorrowedMouseClicked

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
        Borrowed borrowed = new Borrowed();
        borrowed.setId(Integer.parseInt(txtId.getText()));
        borrowed.setIdBooks((Books)cbIDBooks.getSelectedItem());
        borrowed.setIdUsers((Users) cbIDUsers.getSelectedItem());
        borrowed.setDate(dChoserDate.getDate());
        borrowed.setDueDate(dChoserDueDate.getDate());
        borrowed.setReturned(ReturnedTrue.isSelected());
        BorrowedJpaController bjc = new BorrowedJpaController();
        
        try {
            bjc.edit(borrowed);
        } catch (Exception ex) {
            Logger.getLogger(WindowBorrowed.class.getName()).log(Level.SEVERE, null, ex);
        }
        loadTable();

    }//GEN-LAST:event_btnModifyActionPerformed

    private void ReturnedTrueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnedTrueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReturnedTrueActionPerformed

    private void cbIDUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbIDUsersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbIDUsersActionPerformed

    private void cbIDBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbIDBooksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbIDBooksActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ReturnedFalse;
    private javax.swing.JRadioButton ReturnedTrue;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.ButtonGroup btnGroupReturned;
    private javax.swing.JButton btnModify;
    private javax.swing.JComboBox<Object
    > cbIDBooks;
    private javax.swing.JComboBox<Object
    > cbIDUsers;
    private com.toedter.calendar.JDateChooser dChoserDate;
    private com.toedter.calendar.JDateChooser dChoserDueDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel lbIdBook;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDueDate;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblIdUsers;
    private javax.swing.JLabel lblLibrary;
    private javax.swing.JTable tblBorrowed;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
