/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mylibrary;

import controller.UsersJpaController;
import entities.Users;
import java.util.Objects;



import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import javax.swing.text.DocumentFilter;
import javax.swing.text.PlainDocument;
import org.eclipse.persistence.expressions.ExpressionOperator;



/**
 *
 * @author Juan
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Ingreso
     */
    public Login() {
        initComponents();
        PlainDocument doc = (PlainDocument) txtUser.getDocument();
        doc.setDocumentFilter(new MyIntFilter());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUser = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        pwPassword = new javax.swing.JPasswordField();
        Title = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(null);

        txtUser.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });
        getContentPane().add(txtUser);
        txtUser.setBounds(150, 80, 140, 24);

        lblPassword.setText("Password");
        getContentPane().add(lblPassword);
        lblPassword.setBounds(70, 120, 56, 16);

        lblUser.setText("User");
        getContentPane().add(lblUser);
        lblUser.setBounds(100, 90, 27, 16);

        btnLogin.setText("Log in");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin);
        btnLogin.setBounds(170, 170, 70, 24);

        pwPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(pwPassword);
        pwPassword.setBounds(150, 120, 140, 22);

        Title.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        Title.setText("Library");
        getContentPane().add(Title);
        Title.setBounds(150, 20, 100, 32);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        Users user=new Users();
        UsersJpaController ujc = new UsersJpaController();
        //Integer.getInteger(nm)
        if("".equals(String.valueOf(txtUser.getText()))){
            //System.out.println("vacio");
        }
        else{
            user=ujc.findUsers(Integer.parseInt(txtUser.getText()));
            if(Objects.isNull(user)){
                JOptionPane.showMessageDialog(this, "Wrong user or password" );
                return;
            }
            if(user.getPassword().equals(String.valueOf(pwPassword.getPassword()))){
                //System.out.println("bien");
                (new MainWindow(user)).setVisible(true);
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(this, "Wrong user or password" );
                return;
                
            }
            
            //pwPassword.getPassword();
            
        }
        
        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void pwPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwPasswordActionPerformed

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPasswordField pwPassword;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
