/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mylibrary;

import CRUD.CrudAuthor;
import CRUD.CrudBooks;
import CRUD.CrudShelves;
import CRUD.CrudUsers;
import CRUD.WindowBorrowed;
import CRUD.WindowFines;

import java.awt.event.FocusEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import entities.Books;
import entities.Users;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Ricardo
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    private Users logInUser;
    private int borrowedId=-1;//table selected borrowed id       
    public MainWindow(Users user) {
        boolean admin = user.getUserType();
        logInUser=user;
        initComponents();
        this.setResizable(false);
        loadSearchTable();
        
        if(!admin){
            tabbedPane.remove(0);
        }
        tabbedPane.addTab("Edit Borrow",(new WindowBorrowed()));
        tabbedPane.addTab("Edit Fines",(new WindowFines()));
        tabbedPane.addTab("Edit Author",(new CrudAuthor()));
        tabbedPane.addTab("Edit Books",(new CrudBooks()));
        tabbedPane.addTab("Edit Shelves",(new CrudShelves()));
        tabbedPane.addTab("Edit Users",(new CrudUsers()));
        
        
    }
    private void loadSearchTable(){
        /*DefaultTableModel model= new DefaultTableModel();
        //`id`, `title`, `editorial`, `author`, `existences`, `shelve`
        model.addColumn("id");
        model.addColumn("title");
        model.addColumn("editorial");
        model.addColumn("author");
        model.addColumn("existences");
        model.addColumn("shelve");
        List<Books> listBooks = new ArrayList<Books>();
        BooksJpaController bjc =new BooksJpaController();
        listBooks = bjc.findBooksEntities();
        

        String data[]=new String[6];
        for (Books b: listBooks){
            data[0]= String.valueOf(b.getId());
            data[1]= b.getTitle();
            data[2]= b.getEditorial();
            data[3]= b.getAuthor();
            data[4]= String.valueOf(b.getExistences());
            data[5]= b.getShelve();
            System.out.println(b.getTitle().contains("Mate"));
            System.out.println(b.getTitle());
            if(b.getTitle().toLowerCase().contains(String.valueOf(txtSearch.getText()).toLowerCase())){
            model.addRow(data);}
        }
        tblBooksSearch.setModel(model); 
    */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        btnLogOut = new javax.swing.JButton();
        tabbedPane = new javax.swing.JTabbedPane();
        searchPane = new javax.swing.JPanel();
        btnSearch = new javax.swing.JButton();
        btnBorrowBook = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBooksSearch = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(840, 500));
        getContentPane().setLayout(null);

        btnLogOut.setText("Log out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogOut);
        btnLogOut.setBounds(740, 0, 80, 24);

        searchPane.setLayout(null);

        btnSearch.setText("search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        searchPane.add(btnSearch);
        btnSearch.setBounds(550, 20, 80, 24);

        btnBorrowBook.setText("Borrow Book");
        btnBorrowBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrowBookActionPerformed(evt);
            }
        });
        searchPane.add(btnBorrowBook);
        btnBorrowBook.setBounds(350, 400, 120, 24);

        tblBooksSearch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblBooksSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblBooksSearch.setDoubleBuffered(true);
        tblBooksSearch.setVerifyInputWhenFocusTarget(false);
        tblBooksSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBooksSearchMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBooksSearch);

        searchPane.add(jScrollPane1);
        jScrollPane1.setBounds(160, 70, 500, 307);

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        searchPane.add(txtSearch);
        txtSearch.setBounds(190, 20, 330, 30);

        tabbedPane.addTab("Search", searchPane);

        getContentPane().add(tabbedPane);
        tabbedPane.setBounds(0, 0, 840, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBorrowBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrowBookActionPerformed
        // TODO add your handling code here:
        Date d =new Date();
        //d.
        //if(borrowedId!=-1)
    }//GEN-LAST:event_btnBorrowBookActionPerformed

    private void tblBooksSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBooksSearchMouseClicked
        borrowedId= Integer.parseInt(String.valueOf(tblBooksSearch.getValueAt(tblBooksSearch.getSelectedRow(), 0)));
    }//GEN-LAST:event_tblBooksSearchMouseClicked

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed
    //table 2
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        loadSearchTable();
        borrowedId=-1;//set not selected borrowed id       
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        (new Login()).setVisible(true);
        dispose();        
    }//GEN-LAST:event_btnLogOutActionPerformed

    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainWindow().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrowBook;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnSearch;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel searchPane;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTable tblBooksSearch;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
