/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mylibrary;

/**
 *
 * @author Ricardo
 */
public class panelPrueba extends javax.swing.JPanel {

    /**
     * Creates new form panelPrueba
     */
    public panelPrueba() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLibrary = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnModify = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        txtTitle = new javax.swing.JTextField();
        txtEditorial = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblEditorial = new javax.swing.JLabel();
        lblAuthor = new javax.swing.JLabel();
        lblExistences = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        tblBooks = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setLayout(null);

        lblLibrary.setText("Edit Borrowed");
        add(lblLibrary);
        lblLibrary.setBounds(226, 6, 80, 16);

        btnAdd.setText("add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd);
        btnAdd.setBounds(520, 220, 50, 24);

        btnDelete.setText("delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete);
        btnDelete.setBounds(580, 220, 70, 24);

        btnExit.setText("exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        add(btnExit);
        btnExit.setBounds(740, 220, 60, 24);

        btnModify.setText("modify");
        add(btnModify);
        btnModify.setBounds(660, 220, 70, 24);
        add(txtId);
        txtId.setBounds(586, 56, 60, 24);
        add(txtTitle);
        txtTitle.setBounds(586, 86, 220, 24);
        add(txtEditorial);
        txtEditorial.setBounds(586, 116, 220, 24);

        lblId.setText("ID");
        add(lblId);
        lblId.setBounds(516, 56, 12, 16);

        lblTitle.setText("idBook");
        add(lblTitle);
        lblTitle.setBounds(516, 86, 60, 16);

        lblEditorial.setText("idUsers");
        add(lblEditorial);
        lblEditorial.setBounds(516, 116, 44, 16);

        lblAuthor.setText("date");
        add(lblAuthor);
        lblAuthor.setBounds(516, 146, 24, 16);

        lblExistences.setText("DueDate");
        add(lblExistences);
        lblExistences.setBounds(516, 176, 49, 16);

        tblBooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblBooks.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblBooks.setDoubleBuffered(true);
        tblBooks.setVerifyInputWhenFocusTarget(false);
        tblBooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBooksMouseClicked(evt);
            }
        });
        jScrollPane.setViewportView(tblBooks);

        add(jScrollPane);
        jScrollPane.setBounds(6, 36, 500, 307);

        jLabel5.setText("jLabel5");
        add(jLabel5);
        jLabel5.setBounds(670, 410, 41, 16);
        add(jDateChooser2);
        jDateChooser2.setBounds(590, 180, 210, 24);
        add(jDateChooser1);
        jDateChooser1.setBounds(590, 150, 210, 24);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
//        Books books = new Books();
//        books.setAuthor(txtAuthor.getText());
//        books.setEditorial(txtEditorial.getText());
//        books.setExistences(Integer.parseInt(txtExistences.getText()));
//        //books.setId(WIDTH);
//        books.setShelve(txtShelve.getText());
//        books.setTitle(txtTitle.getText());
//        BooksJpaController bjc =new BooksJpaController();
//        bjc.create(books);
//        loadTable();
        /*Book book = new Book(Integer.parseInt(txtId.getText()), txtTitle.getText(),
            txtEditorial.getText(), txtAuthor.getText(),
            Integer.parseInt(txtExistences.getText()), txtShelve.getText());

        //System.out.print(book.toString());
        if(book.add()){
            JOptionPane.showMessageDialog(null,"Succesfully added");
        }
        else{
            JOptionPane.showMessageDialog(null,"Problem");
        }*/

        //txtAuthor.getText();        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
//        try {
//            Books books = new Books();
//            BooksJpaController bjc =new BooksJpaController();
//            System.out.println("entero = "+Integer.parseInt(txtId.getText()));
//            bjc.destroy(Integer.parseInt(txtId.getText()));
//            loadTable();
//
//            // TODO add your handling code here:
//        } catch (NonexistentEntityException ex) {
//            Logger.getLogger(Visual.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    private void tblBooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBooksMouseClicked

//        txtId.setText(String.valueOf(tblBooks.getValueAt(tblBooks.getSelectedRow(), 0)));
//        txtTitle.setText(String.valueOf(tblBooks.getValueAt(tblBooks.getSelectedRow(), 1)));
//        txtEditorial.setText(String.valueOf(tblBooks.getValueAt(tblBooks.getSelectedRow(), 2)));
//        txtAuthor.setText(String.valueOf(tblBooks.getValueAt(tblBooks.getSelectedRow(), 3)));
//        txtExistences.setText(String.valueOf(tblBooks.getValueAt(tblBooks.getSelectedRow(), 4)));
//        txtShelve.setText(String.valueOf(tblBooks.getValueAt(tblBooks.getSelectedRow(), 5)));
    }//GEN-LAST:event_tblBooksMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnModify;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel lblAuthor;
    private javax.swing.JLabel lblEditorial;
    private javax.swing.JLabel lblExistences;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblLibrary;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblBooks;
    private javax.swing.JTextField txtEditorial;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables
}
