/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mylibrary;

import java.awt.event.FocusEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import entities.Books;

/**
 *
 * @author Ricardo
 */
public class Visual extends javax.swing.JFrame {

    /**
     * Creates new form Visual
     */
    public Visual() {
        initComponents();
        loadTable();
        
    }
    private void loadTable(){
        /*DefaultTableModel model= new DefaultTableModel();
            //`id`, `title`, `editorial`, `author`, `existences`, `shelve`
            model.addColumn("id");
            model.addColumn("title");
            model.addColumn("editorial");
            model.addColumn("author");
            model.addColumn("existences");
            model.addColumn("shelve");
            List<Book> listBooks = new ArrayList<Book>();
            listBooks = (new Book()).consult();//get all bookd

            String data[]=new String[6];
            for (Book b: listBooks){
                data[0]= String.valueOf(b.getId());
                data[1]= b.getTitle();
                data[2]= b.getEditorial();
                data[3]= b.getAuthor();
                data[4]= String.valueOf(b.getExistences());
                data[5]= b.getShelve();
                model.addRow(data);
            }
            tblBooks.setModel(model);
            //tblBooks.add
            //tblBooks.getSelectedRow()*/
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLibrary = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnModify = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        txtTitle = new javax.swing.JTextField();
        txtEditorial = new javax.swing.JTextField();
        txtAuthor = new javax.swing.JTextField();
        txtExistences = new javax.swing.JTextField();
        txtShelve = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblEditorial = new javax.swing.JLabel();
        lblAuthor = new javax.swing.JLabel();
        lblExistences = new javax.swing.JLabel();
        lblShelve = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        tblBooks = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(840, 420));
        getContentPane().setLayout(null);

        lblLibrary.setText("Library");
        getContentPane().add(lblLibrary);
        lblLibrary.setBounds(230, 20, 37, 16);

        btnAdd.setText("add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd);
        btnAdd.setBounds(520, 270, 50, 24);

        btnDelete.setText("delete");
        getContentPane().add(btnDelete);
        btnDelete.setBounds(580, 270, 70, 24);

        btnExit.setText("exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit);
        btnExit.setBounds(740, 270, 60, 24);

        btnModify.setText("modify");
        getContentPane().add(btnModify);
        btnModify.setBounds(660, 270, 70, 24);

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        getContentPane().add(txtId);
        txtId.setBounds(590, 70, 60, 24);

        txtTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTitleActionPerformed(evt);
            }
        });
        getContentPane().add(txtTitle);
        txtTitle.setBounds(590, 100, 220, 24);

        txtEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditorialActionPerformed(evt);
            }
        });
        getContentPane().add(txtEditorial);
        txtEditorial.setBounds(590, 130, 220, 24);

        txtAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAuthorActionPerformed(evt);
            }
        });
        getContentPane().add(txtAuthor);
        txtAuthor.setBounds(590, 160, 220, 24);

        txtExistences.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExistencesActionPerformed(evt);
            }
        });
        getContentPane().add(txtExistences);
        txtExistences.setBounds(590, 190, 220, 24);

        txtShelve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtShelveActionPerformed(evt);
            }
        });
        getContentPane().add(txtShelve);
        txtShelve.setBounds(590, 220, 220, 24);

        lblId.setText("ID");
        getContentPane().add(lblId);
        lblId.setBounds(520, 70, 12, 16);

        lblTitle.setText("Title");
        getContentPane().add(lblTitle);
        lblTitle.setBounds(520, 100, 23, 16);

        lblEditorial.setText("Editorial");
        getContentPane().add(lblEditorial);
        lblEditorial.setBounds(520, 130, 45, 16);

        lblAuthor.setText("Author");
        getContentPane().add(lblAuthor);
        lblAuthor.setBounds(520, 160, 35, 16);

        lblExistences.setText("Existences");
        getContentPane().add(lblExistences);
        lblExistences.setBounds(520, 190, 60, 16);

        lblShelve.setText("Shelve");
        getContentPane().add(lblShelve);
        lblShelve.setBounds(520, 220, 37, 16);

        tblBooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblBooks.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblBooks.setDoubleBuffered(true);
        tblBooks.setVerifyInputWhenFocusTarget(false);
        jScrollPane.setViewportView(tblBooks);

        getContentPane().add(jScrollPane);
        jScrollPane.setBounds(10, 50, 500, 307);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAuthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAuthorActionPerformed

    private void txtEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditorialActionPerformed

    private void txtTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTitleActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        Books books = new Books();
        
        
        /*Book book = new Book(Integer.parseInt(txtId.getText()), txtTitle.getText(), 
                txtEditorial.getText(), txtAuthor.getText(),
                Integer.parseInt(txtExistences.getText()), txtShelve.getText());

        //System.out.print(book.toString());
        if(book.add()){
            JOptionPane.showMessageDialog(null,"Succesfully added");
        }
        else{
            JOptionPane.showMessageDialog(null,"Problem");
        }*/
        loadTable();
        //txtAuthor.getText();        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtExistencesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExistencesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExistencesActionPerformed

    private void txtShelveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtShelveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtShelveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Visual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnModify;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel lblAuthor;
    private javax.swing.JLabel lblEditorial;
    private javax.swing.JLabel lblExistences;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblLibrary;
    private javax.swing.JLabel lblShelve;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblBooks;
    private javax.swing.JTextField txtAuthor;
    private javax.swing.JTextField txtEditorial;
    private javax.swing.JTextField txtExistences;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtShelve;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables
}
